"""Plain-language labels and descriptions for Web 工具设置面板."""

from __future__ import annotations

from typing import Any

# 面向普通用户的说明（设置 → 工具）
TOOL_DESCRIPTIONS: dict[str, str] = {
  "get_vehicle_state": "查看车速、是否已开启辅助驾驶、车型等当前行车状态",
  "get_full_vehicle_state": "导出更完整的车辆状态 JSON（内容较多，默认关闭）",
  "read_params": "读取系统参数当前值",
  "list_dp_settings": "列出 Dragonpilot 可调项及当前值，方便对照调优",
  "get_params_catalog": "查看哪些参数 AI 能读、能写、行驶中是否允许",
  "get_agent_memory": "读取 AI 为你记住的车型、备注等跨会话信息",
  "read_onroad_events": "查看最近行车事件与告警，帮助判断异常原因",
  "snapshot_tune_state": "拍一张当前调参状态的快照，便于前后对比",
  "diff_params": "对比两组参数或快照之间的差异",
  "fetch_dashy_settings": "读取 Dashy 界面相关设置",
  "read_manager_log": "查看 openpilot 管理进程日志",
  "grep_log": "在日志里按关键词搜索错误、告警",
  "search_knowledge_base": "在知识库里检索说明文档与调优经验",
  "list_drive_routes": "列出本机已录制的行车路线",
  "analyze_route_summary": "概括一条路线：时长、里程、主要事件等",
  "read_qlog_segment": "读取路线日志中的一小段原始数据",
  "trip_review": "对最近一次或指定行程做复盘分析",
  "list_tune_presets": "查看内置调优预设方案列表",
  "list_scheduled_tasks": "查看已配置的定时任务",
  "list_knowledge_docs": "列出知识库中的文档",
  "cabana_explain_signal": "解释某条 CAN 信号的含义与取值",
  "cabana_analyze": "让 AI 根据 CAN 数据做综合分析",
  "list_dbcs": "列出可用的车辆 CAN 数据库（DBC）",
  "read_dbc_file": "读取某个 DBC 文件内容",
  "list_adaptation_projects": "查看进行中的新车适配草稿",
  "export_adaptation_bundle": "打包导出适配草稿，便于备份或分享",
  "analyze_can_id_pattern": "分析 CAN 报文 ID 规律，辅助认车",
  "compare_fingerprint": "把观测到的 CAN 指纹与已知车型对照",
  "suggest_signals_for_adaptation": "根据车型推荐需要关注的 CAN 信号",
  "get_adaptation_template": "获取 CarState/CarController 适配代码模板",
  "extract_can_ids_from_route": "从某条路线日志提取 CAN 指纹",
  "car_porting_auto_fingerprint": "自动从路线识别车辆固件指纹",
  "car_porting_test_route": "用官方脚本测试某条路线是否匹配车型（需停车）",
  "car_porting_fingerprint_to_draft": "把识别到的指纹保存为适配草稿",
  "car_porting_test_interfaces": "运行车型接口单元测试（需停车）",
  "car_porting_steering_accuracy": "分析转向控制精度，排查 ALKA 问题",
  "car_porting_search_segments_by_can": "在公有库按 CAN 特征搜索相似路段",
  "long_maneuver_report": "生成纵向路试 maneuver 的 HTML 报告",
  "mpc_longitudinal_tuning_report": "生成纵向 MPC 仿真调优报告（无需真车）",
  "lat_maneuver_report": "生成横向路试 maneuver 的 HTML 报告",
  "maneuver_mode_status": "查看路试 maneuver 模式相关参数是否开启",
  "maneuversd_status": "查看 maneuver 后台进程是否在运行",
  "route_time_series": "提取路线中某类信号的时间序列数据",
  "route_fetch_frame": "从路线视频里截取某一帧画面",
  "route_video_info": "查看路线关联视频的分辨率、时长等信息",
  "search_local_routes_for_can": "在本机路线里搜索包含特定 CAN 的片段",
  "comma_auth_status": "检查是否已登录 Comma 账号（用于云路线）",
  "search_car_segments": "在 Comma 公有库搜索其他用户的测试路段",
  "read_bootlog": "读取设备启动日志列表",
  "plotjuggler_data_summary": "概括路线里有哪些可画曲线的数据通道",
  "read_dbc_platform_map": "查看车型平台与 DBC 文件的对应关系",
  "get_host_environment": "识别车机（C3/C3X/C4）或 PC，以及路径、可用工具",
  "pc_launch_plotjuggler": "在电脑上打开 PlotJuggler 看曲线（仅 PC）",
  "pc_launch_replay": "在电脑上回放某条路线（仅 PC）",
  "pc_launch_cabana": "在电脑上打开桌面版 Cabana（仅 PC）",
  "pc_launch_sim_bridge": "启动仿真桥接，用于开发调试（仅 PC）",
  "pc_auth_login_hint": "提示如何在 PC 上登录 Comma 账号",
  "pc_capture_route_context": "抓取当前 PC 工具正在查看的路线数据摘要",
  "pc_list_tool_sessions": "列出电脑上已启动的 PlotJuggler/Replay 等会话",
  "pc_get_tool_session": "查看某个 PC 工具会话的详情与数据快照",
  "pc_launch_jotpluggler": "在电脑上打开 JotPluggler 看 GPS/地图类曲线",
  "pc_launch_replay_stream": "启动 Replay 并向本机推送 ZMQ 数据流",
  "pc_launch_plotjuggler_stream": "PlotJuggler 订阅 Replay 实时数据流",
  "pc_launch_jotpluggler_stream": "JotPluggler 订阅 Replay 实时数据流",
  "pc_launch_replay_viz_stream": "Replay + 可视化工具一键联调",
  "pc_launch_replay_ui": "打开 Replay 图形界面（仅 PC）",
  "pc_launch_camerastream": "打开摄像头流调试工具（仅 PC）",
  "route_export_clip": "把路线片段导出为 MP4 视频",
  "route_extract_audio": "从路线视频提取音频文件",
  "route_ublox_summary": "概括路线里 GPS 模块（Ublox）相关日志",
  "route_can_stats": "统计路线里 CAN 报文数量与常见 ID（只读，不连硬件）",
  "compare_route_signals": "对比两条路线的信号统计，找调优差异",
  "batch_route_summary": "批量概括最近几条路线",
  "search_route_messages": "在路线日志里搜索特定消息或字段",
  "list_plotjuggler_layouts": "列出 PlotJuggler 预设曲线布局",
  "list_jotpluggler_layouts": "列出 JotPluggler 预设布局",
  "get_build_info": "查看当前 fork 的 git 版本、模型文件等构建信息",
  "list_managed_processes": "查看 openpilot 各后台进程是否在运行",
  "get_webcam_dev_setup": "查看 PC 上用摄像头仿真的配置说明",
  "get_devsync_hint": "查看如何把代码同步到车机的说明",
  "pc_devsync_status": "检查 devsync 前置条件（rsync/git/ssh、车机 SSH），不执行同步",
  "openpilotci_segment_url": "生成 OpenpilotCI 测试片段链接",
  "live_cereal_summary": "概括当前实时 cereal 消息（开发调试用）",
  "lookup_secoc_tier": "查询丰田 SecOC 密钥难度档位",
  "suggest_tune_from_route": "根据路线表现给出调参建议",
  "save_tune_snapshot": "保存当前全部调参，便于以后一键恢复",
  "restore_tune_snapshot": "恢复到之前保存的调参快照",
  "list_tune_snapshots": "列出已保存的调参快照",
  "reindex_knowledge_base": "重建知识库向量索引（文档很多时较慢）",
  "write_params": "修改系统参数（仅停车且需你确认）",
  "apply_tune_preset": "一键应用某套调优预设（仅停车）",
  "select_driving_model": "切换驾驶神经网络模型（仅停车）",
  "update_agent_memory": "让 AI 记住你的车型、偏好等备注",
  "manage_knowledge_doc": "添加、修改或删除知识库文档",
  "manage_scheduled_task": "创建或修改定时自动任务",
  "save_adaptation_draft": "保存车辆适配草稿",
  "run_shell": "运行白名单内的只读终端命令（如 uptime、查日志）",
  "restart_service": "重启 aid/ui/manager 等服务（仅停车）",
  "restart_ui": "重启车机界面（仅停车）",
  "reboot_device": "重启 comma/AGNOS 整机",
  "shutdown_device": "关闭 comma/AGNOS 设备电源",
  "manager_control": "启动/停止/重启 manager 或 scons 编译",
  "git_status": "查看 openpilot 仓库 Git 状态",
  "git_diff": "查看 Git 代码差异",
  "git_list_branches": "列出本地与远程 Git 分支",
  "git_checkout": "切换到指定 Git 分支（工作区有未提交改动时会拒绝）",
  "git_pull": "从远程拉取 Git 更新",
  "apply_tune_from_route": "根据路线建议调参并写入（自动快照）",
  "compare_tune_ab": "调参前后两条路线 A/B 对比与建议",
  "pc_devsync_run": "PC 上一键 devsync 同步代码到车机",
  "live_can_capture": "采集实时 CAN 报文供分析",
  "network_diagnostics": "WiFi、ping、SSH、comma 登录联机诊断",
  "list_audit_trail": "查看 AI 工具调用与写入审计记录",
  "list_plugins": "查看已加载的 op助手 插件",
  "git_fetch": "从远程获取 Git 更新（不合并）",
  "git_stash": "暂存未提交的 Git 改动",
  "git_stash_pop": "恢复最近一次 Git stash",
  "git_commit": "提交 Git 改动",
  "score_route_tune": "路线调参舒适度量化评分",
  "score_tune_session": "调参前后路线评分对比",
  "route_event_timeline": "路线 engage/告警事件时间线",
  "device_health": "磁盘、温度、设备型号（tici/tizi/mici）与 AGNOS 版本",
  "panda_status": "Panda 连接与固件状态",
  "list_tune_passport": "调参改动历史（调参护照）",
  "manage_param_watchlist": "管理重点监视的参数列表",
  "check_param_watchlist": "检查监视参数是否漂移",
  "generate_adaptation_pr_draft": "生成车辆适配 PR 描述草稿",
  "post_drive_voice_summary": "停车后文字/语音行程简报",
  "sync_knowledge_from_docs": "把仓库文档同步进知识库",
  "git_push": "推送 Git 到远程仓库",
  "ota_status": "查看 OTA/版本更新状态",
  "batch_compare_routes_tune": "批量路线调参评分排名",
  "run_pytest": "运行 pytest 单元测试（PC）",
  "run_scons_build": "运行 scons 编译（PC）",
  "ssh_readonly_exec": "SSH 只读诊断命令",
  "list_comma_devices": "列出 Comma 云设备",
  "list_comma_routes": "列出 Comma 云路线",
  "analyze_route_vision": "路线抽帧与亮度分析",
  "plotjuggler_apply_layout": "解析并应用 PlotJuggler 布局",
  "search_memory_semantic": "语义搜索长期记忆",
  "get_tsk_manager_status": "TSK SecOC 流水线状态（密钥/CAN/DataFlash）",
  "tsk_find_and_install_key": "查找并安装丰田 SecOC 密钥",
  "tsk_extract_key": "TSK 一键 UDS 提取密钥",
  "tsk_install_secoc_key": "手动安装 SecOC 密钥",
  "tsk_uninstall_key": "卸载已安装的 SecOC 密钥",
  "tsk_start_can_collect": "启动 CAN 报文采集",
  "tsk_start_dataflash_dump": "启动 DataFlash 导出",
  "tsk_clear_cache": "清除 CAN/DataFlash 提取缓存",
  "konik_connect_status": "Konik 云配对进度（SSH / 密钥 / DongleId）",
  "konik_generate_device_keys": "生成 Konik 设备 RSA 密钥（克隆机必做）",
  "konik_reset_dongle_id": "清除旧 DongleId，向 Konik 重新注册",
  "konik_register_device": "调用 registration.py 向 Konik API 注册设备",
  "konik_connect_pipeline": "一条龙：密钥 → 清 DongleId → 注册 → 配对链接",
}

# 更友好的显示名（覆盖 TOOL_META 里过于技术化的 label）
TOOL_LABEL_OVERRIDES: dict[str, str] = {
  "get_full_vehicle_state": "完整车辆状态",
  "list_dp_settings": "Dragonpilot 可调项",
  "read_onroad_events": "行车事件与告警",
  "grep_log": "日志关键词搜索",
  "car_porting_auto_fingerprint": "自动识别车辆指纹",
  "car_porting_test_route": "测试路线是否匹配车型",
  "car_porting_fingerprint_to_draft": "保存指纹到草稿",
  "car_porting_test_interfaces": "车型接口自检",
  "car_porting_search_segments_by_can": "公有库搜相似路段",
  "long_maneuver_report": "纵向路试报告",
  "mpc_longitudinal_tuning_report": "纵向仿真调优报告",
  "lat_maneuver_report": "横向路试报告",
  "maneuver_mode_status": "路试模式状态",
  "maneuversd_status": "路试后台进程",
  "plotjuggler_data_summary": "路线曲线数据概览",
  "read_dbc_platform_map": "车型与 DBC 对照表",
  "pc_launch_plotjuggler": "打开 PlotJuggler（PC）",
  "pc_launch_replay": "打开 Replay（PC）",
  "pc_launch_cabana": "打开桌面 Cabana（PC）",
  "pc_launch_sim_bridge": "启动仿真桥（PC）",
  "pc_auth_login_hint": "Comma 账号登录指引",
  "pc_capture_route_context": "抓取 PC 工具数据",
  "pc_list_tool_sessions": "PC 工具会话列表",
  "pc_get_tool_session": "PC 工具会话详情",
  "pc_launch_jotpluggler": "打开 JotPluggler（PC）",
  "pc_launch_replay_stream": "Replay 数据流（PC）",
  "pc_launch_plotjuggler_stream": "PlotJuggler 联调流（PC）",
  "pc_launch_jotpluggler_stream": "JotPluggler 联调流（PC）",
  "pc_launch_replay_viz_stream": "Replay 可视化联调（PC）",
  "pc_launch_replay_ui": "Replay 图形界面（PC）",
  "pc_launch_camerastream": "摄像头流调试（PC）",
  "route_ublox_summary": "GPS 模块日志摘要",
  "route_can_stats": "路线 CAN 统计",
  "compare_route_signals": "两条路线信号对比",
  "batch_route_summary": "最近路线批量摘要",
  "search_route_messages": "路线消息搜索",
  "list_plotjuggler_layouts": "PlotJuggler 布局列表",
  "list_jotpluggler_layouts": "JotPluggler 布局列表",
  "get_build_info": "版本与构建信息",
  "list_managed_processes": "后台进程状态",
  "get_webcam_dev_setup": "PC 摄像头仿真说明",
  "get_devsync_hint": "代码同步到车机说明",
  "pc_devsync_status": "Devsync 同步前体检",
  "openpilotci_segment_url": "CI 测试片段链接",
  "live_cereal_summary": "实时消息概览",
  "lookup_secoc_tier": "丰田 SecOC 难度",
  "suggest_tune_from_route": "根据路线给调参建议",
  "reindex_knowledge_base": "重建知识库索引",
  "run_shell": "只读终端诊断",
}


def enrich_tool_meta_for_ui(meta: dict[str, dict[str, Any]]) -> dict[str, dict[str, Any]]:
  out: dict[str, dict[str, Any]] = {}
  for name, m in meta.items():
    entry = dict(m)
    if name in TOOL_LABEL_OVERRIDES:
      entry["label"] = TOOL_LABEL_OVERRIDES[name]
    entry["description"] = TOOL_DESCRIPTIONS.get(name, entry.get("description", ""))
    out[name] = entry
  return out
