"""HTTP route registration for op助手."""

from aiohttp import web

from ai.server.handlers import api as h
from ai.server.handlers import phase2 as phase2_handlers
from ai.server.handlers import harness_handlers
from ai.server.routes.agents import register_agent_routes


def register_routes(app: web.Application, *, json_response) -> None:
  register_agent_routes(app, json_response=json_response)

  app.router.add_get("/api/ai/bootstrap", h.api_bootstrap)
  app.router.add_get("/api/ai/status", h.api_status)
  app.router.add_get("/api/ai/providers", h.api_providers)
  app.router.add_get("/api/ai/config", h.api_get_config)
  app.router.add_post("/api/ai/config", h.api_post_config)
  app.router.add_get("/api/ai/models", h.api_models)
  app.router.add_post("/api/ai/models", h.api_models)
  app.router.add_get("/api/ai/test_connection", h.api_test_connection)
  app.router.add_post("/api/ai/test_connection", h.api_test_connection)
  app.router.add_get("/api/ai/test", h.api_test_connection)
  app.router.add_post("/api/ai/test", h.api_test_connection)
  app.router.add_post("/api/ai/chat", h.api_chat)
  app.router.add_get("/api/ai/chat/jobs", h.api_chat_jobs)
  app.router.add_post("/api/ai/chat/jobs", h.api_chat_jobs)
  app.router.add_get("/api/ai/chat/jobs/{job_id}", h.api_chat_job_detail)
  app.router.add_delete("/api/ai/chat/jobs/{job_id}", h.api_chat_job_detail)
  app.router.add_post("/api/ai/shell", h.api_shell)
  app.router.add_get("/api/ai/state", h.api_state)
  app.router.add_get("/api/ai/usage", h.api_usage)
  app.router.add_get("/api/ai/skills", h.api_skills)
  app.router.add_post("/api/ai/skills", h.api_skills)
  app.router.add_get("/api/ai/tools", h.api_tools_meta)
  app.router.add_get("/api/ai/memory", h.api_memory)
  app.router.add_post("/api/ai/memory", h.api_memory)
  app.router.add_get("/api/ai/scheduler", h.api_scheduler)
  app.router.add_post("/api/ai/scheduler", h.api_scheduler)
  app.router.add_get("/api/ai/write/pending", h.api_write_pending)
  app.router.add_post("/api/ai/write/confirm", h.api_write_confirm)
  app.router.add_get("/api/ai/tune_passport", h.api_tune_passport)
  app.router.add_post("/api/ai/tune/compare", h.api_tune_compare)
  app.router.add_get("/api/ai/rag", h.api_rag)
  app.router.add_post("/api/ai/rag", h.api_rag)
  app.router.add_get("/api/ai/sessions", h.api_sessions)
  app.router.add_post("/api/ai/sessions", h.api_sessions)
  app.router.add_get("/api/ai/dev-assets", h.api_dev_assets)
  app.router.add_get("/api/ai/dev-assets/{kind}/{name}", h.api_dev_assets)
  app.router.add_get("/api/ai/files/search", h.api_files_search)
  app.router.add_get("/api/ai/files/content", h.api_files_content)
  app.router.add_get("/api/ai/context/url", h.api_context_url)
  app.router.add_get("/api/ai/context/branch", h.api_context_branch)
  app.router.add_get("/api/ai/context/session", h.api_context_session)
  app.router.add_get("/api/ai/dev-cache", h.api_dev_cache)
  app.router.add_post("/api/ai/dev-cache", h.api_dev_cache)
  app.router.add_post("/api/ai/model-hub/fetch-models", h.api_model_hub_fetch)
  app.router.add_post("/api/ai/model-hub/test-account", h.api_model_hub_test)
  app.router.add_get("/api/ai/pc-sessions", h.api_pc_sessions)
  app.router.add_get("/api/ai/workflows", h.api_workflows)
  app.router.add_get("/api/ai/notifications", h.api_notifications)
  app.router.add_post("/api/ai/notifications", h.api_notifications)
  app.router.add_get("/api/ai/feedback", h.api_feedback)
  app.router.add_post("/api/ai/feedback", h.api_feedback)
  app.router.add_get("/api/ai/adaptation/{project_id}/bundle", h.api_adaptation_bundle)
  app.router.add_get("/api/ai/package/version", h.api_package_version)
  app.router.add_post("/api/ai/package/update", h.api_package_update)
  app.router.add_get("/api/ai/fork/detect", h.api_fork_detect)
  app.router.add_post("/api/ai/fork/analyze", h.api_fork_analyze)
  app.router.add_post("/api/ai/fork/sync", h.api_fork_sync)
  app.router.add_post("/api/ai/fork/run", h.api_fork_run_stream)
  app.router.add_get("/api/ai/publish", h.api_publish)
  app.router.add_post("/api/ai/publish", h.api_publish)
  app.router.add_get("/api/ai/issues", h.api_issues)
  app.router.add_post("/api/ai/issues", h.api_issues)
  app.router.add_post("/api/ai/onboarding/profile", h.api_onboarding_profile)
  app.router.add_post("/api/ai/onboarding/complete", h.api_onboarding_complete)
  app.router.add_post("/api/ai/integrate", h.api_integrate_openpilot)
  app.router.add_get("/api/ai/device/trust", phase2_handlers.api_device_trust)
  app.router.add_post("/api/ai/device/pair", phase2_handlers.api_device_pair)
  app.router.add_delete("/api/ai/device/{device_id}", phase2_handlers.api_device_revoke)
  app.router.add_get("/api/ai/canvas", phase2_handlers.api_canvas)
  app.router.add_get("/api/ai/workspace", phase2_handlers.api_workspace)
  app.router.add_post("/api/ai/workspace", phase2_handlers.api_workspace_write)
  app.router.add_get("/api/ai/usage/detail", phase2_handlers.api_usage_detail)
  app.router.add_get("/api/ai/sessions/search", phase2_handlers.api_platform_sessions_search)
  app.router.add_get("/api/ai/mcp", phase2_handlers.api_platform_mcp)
  app.router.add_post("/api/ai/mcp", phase2_handlers.api_platform_mcp)
  app.router.add_get("/api/ai/learned-skills", phase2_handlers.api_platform_learned_skills)
  app.router.add_post("/api/ai/learned-skills", phase2_handlers.api_platform_learned_skills)
  app.router.add_get("/api/ai/toolsets", phase2_handlers.api_platform_toolsets)
  app.router.add_get("/api/ai/platform/backup", phase2_handlers.api_platform_backup)
  app.router.add_post("/api/ai/platform/backup", phase2_handlers.api_platform_backup)
  app.router.add_get("/api/ai/platform/workspace-health", phase2_handlers.api_platform_workspace_health)
  app.router.add_post("/api/ai/platform/workspace-health", phase2_handlers.api_platform_workspace_health)
  app.router.add_get("/api/ai/platform/evolution", phase2_handlers.api_platform_evolution)
  app.router.add_post("/api/ai/platform/evolution", phase2_handlers.api_platform_evolution)
  app.router.add_post("/api/ai/scheduler/nl", phase2_handlers.api_scheduler_nl)
  app.router.add_get("/api/ai/harness/config", harness_handlers.api_harness_config)
  app.router.add_post("/api/ai/harness/config", harness_handlers.api_harness_config)
  app.router.add_get("/api/ai/audit", harness_handlers.api_audit_trail)
  app.router.add_get("/api/ai/transcript", harness_handlers.api_transcript)
  app.router.add_get("/api/ai/transcript/recover", harness_handlers.api_transcript)
  app.router.add_get("/api/ai/usage/summary", harness_handlers.api_usage_summary)
  app.router.add_get("/api/ai/profile/sync", harness_handlers.api_profile_sync)
  app.router.add_post("/api/ai/profile/sync", harness_handlers.api_profile_sync)
  app.router.add_get("/api/ai/workflows/custom", harness_handlers.api_workflows_custom)
  app.router.add_put("/api/ai/workflows/custom", harness_handlers.api_workflows_custom)
  app.router.add_post("/api/ai/workflows/custom", harness_handlers.api_workflows_custom)
  from ai.server.handlers import consumer as consumer_handlers
  app.router.add_get("/api/ai/consumer/wizards", consumer_handlers.api_consumer_wizards)
  app.router.add_get("/api/ai/consumer/wizards/{wizard_id}/start", consumer_handlers.api_consumer_wizard_start)
  app.router.add_post("/api/ai/consumer/wizards/{wizard_id}/start", consumer_handlers.api_consumer_wizard_start)
  app.router.add_get("/api/ai/consumer/lexicon", consumer_handlers.api_consumer_lexicon)
  app.router.add_post("/api/ai/consumer/preview-params", consumer_handlers.api_consumer_preview_params)
