"""Platform tools domain."""

from __future__ import annotations

MODULES = (
  "ai.tools.domains.platform.audit_store",
  "ai.tools.domains.platform.bug_report_tools",
  "ai.tools.domains.platform.catalog_builder",
  "ai.tools.domains.platform.consumer_tools",
  "ai.tools.domains.platform.consumer_wizards",
  "ai.tools.domains.platform.device_health_tools",
  "ai.tools.domains.platform.device_hw_tools",
  "ai.tools.domains.platform.display_device_tools",
  "ai.tools.domains.platform.evolution_reflect",
  "ai.tools.domains.platform.fs_tools",
  "ai.tools.domains.platform.health_check_tools",
  "ai.tools.domains.platform.issue_template_lib",
  "ai.tools.domains.platform.issue_tools",
  "ai.tools.domains.platform.model_manager_tools",
  "ai.tools.domains.platform.network_tools",
  "ai.tools.domains.platform.notifications",
  "ai.tools.domains.platform.op_run",
  "ai.tools.domains.platform.osm_tools",
  "ai.tools.domains.platform.panda_flash_tools",
  "ai.tools.domains.platform.param_write",
  "ai.tools.domains.platform.params_policy",
  "ai.tools.domains.platform.platform_backup",
  "ai.tools.domains.platform.platform_extensions",
  "ai.tools.domains.platform.publish_tools",
  "ai.tools.domains.platform.publish_units",
  "ai.tools.domains.platform.scheduler",
  "ai.tools.domains.platform.scheduler_actions",
  "ai.tools.domains.platform.session_index",
  "ai.tools.domains.platform.session_store",
  "ai.tools.domains.platform.skill_evaluation",
  "ai.tools.domains.platform.skill_evolution",
  "ai.tools.domains.platform.skill_learning",
  "ai.tools.domains.platform.sp_tool_extensions",
  "ai.tools.domains.platform.ssh_tools",
  "ai.tools.domains.platform.system_control_tools",
  "ai.tools.domains.platform.system_info_tools",
  "ai.tools.domains.platform.tool_desc_store",
  "ai.tools.domains.platform.tool_ui_meta",
  "ai.tools.domains.platform.translation_tools",
  "ai.tools.domains.platform.viz_layout_tools",
  "ai.tools.domains.platform.voice_summary_tools",
  "ai.tools.domains.platform.webui_tools",
  "ai.tools.domains.platform.workflows",
  "ai.tools.domains.platform.workspace_enrich",
  "ai.tools.domains.platform.write_pending",
)

__all__ = ["MODULES"]
