name: Build All Tinygrad Models and Push to GitLab

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow from'
        required: false
        default: 'master-new'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      json_file: ${{ steps.get-json.outputs.json_file }}
      model_matrix: ${{ steps.set-matrix.outputs.model_matrix }}
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}

      - name: Add GitLab.com SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts

      - name: Checkout docs repo (sunnypilot-docs, gh-pages)
        uses: actions/checkout@v4
        with:
          repository: sunnypilot/sunnypilot-docs
          ref: gh-pages
          path: docs
          ssh-key: ${{ secrets.CI_SUNNYPILOT_DOCS_PRIVATE_KEY }}

      - name: Clone GitLab docs repo
        env:
          GIT_SSH_COMMAND: 'ssh -o UserKnownHostsFile=~/.ssh/known_hosts'
        run: |
          echo "Cloning GitLab"
          git clone --depth 1 --filter=tree:0 --sparse git@gitlab.com:sunnypilot/public/docs.sunnypilot.ai2.git gitlab_docs
          cd gitlab_docs
          git checkout main
          cd ..

      - name: Set next recompiled dir
        id: set-recompiled
        run: |
          cd gitlab_docs
          echo "checkout models/"
          git sparse-checkout set --no-cone models/
          git checkout main
          cd models
          latest_dir=$(ls -d recompiled* 2>/dev/null | sed -E 's/recompiled([0-9]+)/\1/' | sort -n | tail -1)
          if [[ -z "$latest_dir" ]]; then
            next_dir=1
          else
            next_dir=$((latest_dir+1))
          fi
          recompiled_dir="recompiled${next_dir}"
          if [ -d "$recompiled_dir" ]; then
            echo "ERROR: $recompiled_dir already exists in GitLab repo"
            exit 1
          fi
          mkdir -p "$recompiled_dir"
          touch "$recompiled_dir/.gitkeep"
          echo "RECOMPILED_DIR=$recompiled_dir" >> $GITHUB_ENV
          echo "Created new recompiled dir: $recompiled_dir"
          cd ../..

      - name: Get next JSON version to use (from GitHub docs repo)
        id: get-json
        run: |
          cd docs/docs
          latest=$(ls driving_models_v*.json | sed -E 's/.*_v([0-9]+)\.json/\1/' | sort -n | tail -1)
          next=$((latest+1))
          json_file="driving_models_v${next}.json"
          cp "driving_models_v${latest}.json" "$json_file"
          echo "json_file=docs/docs/$json_file" >> $GITHUB_OUTPUT
          echo "SRC_JSON_FILE=docs/docs/driving_models_v${latest}.json" >> $GITHUB_ENV
      - name: Extract tinygrad models
        id: set-matrix
        working-directory: docs/docs
        run: |
          jq -c '[.bundles[] | select(.runner=="tinygrad") | {ref, display_name, is_20hz}]' "$(basename "${SRC_JSON_FILE}")" > matrix.json
          echo "model_matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  get_and_build:
    needs: [setup]
    uses: ./.github/workflows/sunnypilot-build-model.yaml
    strategy:
      matrix:
        model: ${{ fromJson(needs.setup.outputs.model_matrix) }}
    name: Model [${{ matrix.model.display_name }}] from ref [${{ matrix.model.ref }}]
    with:
      upstream_branch: ${{ matrix.model.ref }}
      custom_name: ${{ matrix.model.display_name }}
      is_20hz: ${{ matrix.model.is_20hz || true }}
    secrets: inherit

  push_results:
    needs: [setup, get_and_build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download all model artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: model-*
          path: output
      - run: |
          ARTIFACT_DIR="gitlab_docs/models/$RECOMPILED_DIR"
          mkdir -p "$ARTIFACT_DIR"
          for name in $(ls output); do
            mkdir -p "$ARTIFACT_DIR/$name"
            cp -r output/$name/* "$ARTIFACT_DIR/$name/"
          done

      - name: Push recompiled dir to GitLab
        env:
          GITLAB_SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
        run: |
          cd gitlab_docs
          git checkout main
          mkdir -p models/"$(basename $RECOMPILED_DIR)"
          git add models/"$(basename $RECOMPILED_DIR)"
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Add $(basename $RECOMPILED_DIR) from build-all-tinygrad-models"
          git push origin main

      - name: Run json_parser.py to update JSON
        run: |
          python3 docs/json_parser.py \
            --json-path "${{ needs.setup.outputs.json_file }}" \
            --recompiled-dir "gitlab_docs/models/$RECOMPILED_DIR"

      - name: Push updated JSON to GitHub docs repo
        run: |
          cd docs
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout gh-pages
          git add docs/"$(basename ${{ needs.setup.outputs.json_file }})"
          git commit -m "Create $(basename ${{ needs.setup.outputs.json_file }}) after recompiling models" || echo "No changes to commit"
          git push origin gh-pages
